---
# install sshd
- hosts: all

  tasks:
  - name: allow password-less login for root
    lineinfile:
      name: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: 'PermitRootLogin without-password'

  - name: disable password-based login for everyone
    lineinfile:
      name: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication'
      line: 'PasswordAuthentication no'

  - name: copy pub ssh keys
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

  - name: restart sshd
    service:
      name: sshd
      state: restarted

