---
# install desktop

- name: install desktop packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items: "{{desktop_packages}}"
  become: true

- name: create config directorys
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items: "{{desktop_conf_dir}}"

- name: install vim-plug
  get_url:
    url: "{{item.link}}"
    dest: "{{item.dest}}"
    mode: 0755
  with_items: "{{desktop_vim_plug}}"

- name: install source-code-pro from github
  git:
    repo: "{{item.link}}"
    dest: "{{item.dest}}"
    accept_hostkey: yes
    version: release
    clone: yes
  with_items: "{{desktop_font}}"
  become: true

- name: update font cache
  shell: fc-cache -f -v /usr/share/fonts/adobe-fonts/source-code-pro

- name: check if qutebrowser is installed
  command: dpkg -s qutebrowser | grep 'installed'
  register: "qutebrowser_check"
  ignore_errors: true

- name: print var
  debug:
    msg: "qutebrowser installed? A: {{qutebrowser_check}}"
  when: "qutebrowser_check == 1"

#- name: install qutebrowser if necessary
#  include: qutebrowser.yml
#  when: '"qutebrowser_check" == 1'

- name: link dotfiles
  template:
    src: "{{role_path}}/templates/{{item.file}}"
    dest: "{{item.dest}}"
    state: link
  with_items: "{{desktop_dotfiles}}"


#- include: handlers/main.yml

