---
# install openjdk

- name: add backports repo for jessie
  apt_repository:
   repo: "{{openjdk_repo}}"
   state: present

- name: install openjdk
  apt:
    name: "{{item}}"
    state: present
    default_release: "jessie-backports"
  with_items: "{{openjdk_packages}}"

# - include: handlers/main.yml
