---
#vars for desktop

desktop_packages:
  - "neovim"
  - "htop"
  - "chromium"
  - "tmux"
  - "mpv"
  - "curl"

desktop_dotfiles:
  - { dest: '~/.Xresources', file: 'Xresources.j2'}
  - { dest: '~/.Xresources.colors', file: 'Xresources.colors.j2'}
  - { dest: '~/.bashrc', file: 'bashrc.j2'}
  - { dest: '~/.xinitrc', file: 'xinitrc.j2'}
  - { dest: '~/.config/nvim/init.vim', file: 'init.vim.j2'}
  - { dest: '~/.config/tmux/tmux.conf', file: 'tmux.conf.j2'}

desktop_conf_dir:
  - "~/.config/nvim"
  - "~/.config/tmux"


