---
#vars for desktop

desktop_packages:
  - "neovim"
  - "htop"
  - "chromium"
  - "tmux"
  - "mpv"
  - "curl"
  - "xmonad"
  - "rofi"
  - "ranger"

desktop_dotfiles:
  - { dest: '~/.Xresources', file: 'Xresources.j2'}
  - { dest: '~/.Xresources.colors', file: 'Xresources.colors.j2'}
  - { dest: '~/.bashrc', file: 'bashrc.j2'}
  - { dest: '~/.xinitrc', file: 'xinitrc.j2'}
  - { dest: '~/.config/nvim/init.vim', file: 'init.vim.j2'}
  - { dest: '~/.config/tmux/tmux.conf', file: 'tmux.conf.j2'}
  - { dest: '~/.xmonad/xmonad.hs', file: 'xmonad.hs.j2'}

desktop_conf_dir:
  - "~/.config/nvim"
  - "~/.config/tmux"
  - "~/.xmonad"
  - "~/.local/share/nvim/site/autoload"

desktop_vim-plug:
  - { dest: '~/.local/share/nvim/site/autoload/plug.vim', link: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'}

desktop_font:
  - { dest: '/usr/share/fonts/adobe-fonts/source-code-pro', link: 'https://github.com/adobe-fonts/source-code-pro.git'}

desktop_qutebrowser:
  dependencies:
    - "python3-lxml"
    - "python-tox"
    - "python3-pyqt5"
    - "python3-pyqt5.qtwebkit"
    - "python3-pyqt5.qtquick"
    - "python3-sip"
    - "python3-jinja2"
    - "python3-pygments"
    - "python3-yaml"
    - "python3-pyqt5.qtsql"
    - "libqt5sql5-sqlite"
    - "python3-pyqt5.qtopengl"
    - "python3-pyqt5.qtwebengine"
  qutebrowser_link: https://github.com/qutebrowser/qutebrowser/releases/download/v0.11.0/qutebrowser_0.11.0-1_all.deb
  qutebrowser_dest: /tmp/qutebrowser
  pypeg2_link: https://qutebrowser.org/python3-pypeg2_2.15.2-1_all.deb
  pypeg2_dest: /tmp/python3-pypeg2
