---
# install jenkins

- name: install jenkins dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items: '{{jenkins_dependencies}}'

- name: import jenkins key
  apt_key:
    url: "{{jenkins_keyserver}}"
    state: present

- name: add jenkins repo
  apt_repository:
    repo: "{{jenkins_repo}}"
    state: present

- name: install jenkins
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{jenkins_packages}}"

- name: disable login for jenkins webgui
  lineinfile:
    path: /var/lib/jenkins/config.xml
    regexp: '^<useSecurity>'
    line: '<useSecurity>false</useSecurity>'

- include: handlers/main.yml
