---
# install dnsmasq

- name: install dnsmasq
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{dnsmasq_packages}}"

- name: copy dnsmasq.conf
  template:
    src: ../templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644

- name: copy resolv.conf
  template:
    src: ../templates/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644

- include: handlers/main.yml

