---
# install docker

- name: install docker dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{docker_dependencies}}"

- name: import docker key
  apt_key:
    url: "{{docker_keyserver}}"
    state: present

- name: add docker repo
  apt_repository:
    repo: "{{docker_repo}}"
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{docker_packages}}"

- name: install docker-py via pip
  pip:
    name: "{{item}}"
  with_items: "{{docker_pip_packages}}"

- include: handlers/main.yml

