---
# this role installs java

#- name: apt-get update as a separate step
#  apt:
#    update_cache: yes

- name: import key used by apt
  apt_key:
    keyserver: "{{ java_keyserver }}"
    id: "{{ java_key }}"
    state: present

- name: add java repo
  apt_repository:
    repo: "{{ java_repo }}"
    state: present
    update_cache: yes
    filename: "{{ java_sources_list }}"

- name: accept oracle jdk license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: 'select'

- name: install java
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ java_packages }}"
  #notify: start java

#- include: handlers/main.yml
