---
# install base

- name: set hostname
  hostname:
    name: "{{hostname}}"
  when: hostname is defined

- name: install base_packages
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{base_packages}}"

- name: apt update
  apt:
    update_cache: yes

- name: remove template user
  user:
    name: template
    state: present
    shell: /bin/false

- include: sshd.yml
