---
# install sshd

- name: allow password-less login for root
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin without-password'

- name: disable password-based login for everyone
  lineinfile:
    name: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  
- name: restart sshd
  service:
    name: sshd
    state: restarted
