---
# this role installs elasticsearch

#- name: apt-get update as a separate step
#  apt:
#    update_cache: yes

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: import key used by apt
  apt_key:
    url: "{{ es_keyserver }}"
    state: present

- name: add es repo
  apt_repository:
    repo: "{{ es_repo }}"
    state: present
    update_cache: yes
    filename: "{{ es_sources_list }}"

- name: install es
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: modify es config
  lineinfile:
    path: "{{ es_config_file }}"
    regexp: "cluster.name"
    line: "cluster.name = graylog"
  notify: start es

- include: handlers/main.yml
